# version: '1.0.0'

services:
  passwordManager:
    # image: passwordManager
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
